"""
================================================================================
Smoke Test -- Phase 2: Predictive Engine (TFT)
================================================================================

Validates all Phase 2 components using synthetic data generated by Phase 1's
test infrastructure.  Tests cover:
    1. DatasetBuilder: DataFrame preparation and TimeSeriesDataSet creation
    2. ModelBuilder: TFT instantiation with QuantileLoss
    3. TrainingPipeline: hardware detection, callback setup
    4. TFTPredictor: prediction extraction and structuring
    5. End-to-end: full pipeline on synthetic data (1-epoch smoke test)

Requirements:
    pip install torch pytorch-forecasting pytorch-lightning

Run:
    python test_predictive_engine.py
================================================================================
"""

import os
import shutil
import sys
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd

# ---- Check dependencies before running ------------------------------------
def check_dependencies():
    """Verify all Phase 2 dependencies are installed."""
    missing = []
    try:
        import torch
    except ImportError:
        missing.append("torch")
    try:
        import pytorch_forecasting
    except ImportError:
        missing.append("pytorch-forecasting")
    try:
        try:
            import lightning.pytorch
        except ImportError:
            import pytorch_lightning
    except ImportError:
        missing.append("pytorch-lightning (or lightning)")

    if missing:
        print(f"Missing dependencies: {missing}")
        print("Install with:")
        print("  pip install torch pytorch-forecasting pytorch-lightning")
        print("\nSkipping Phase 2 tests.")
        sys.exit(0)

check_dependencies()

# ---- Now import Phase 2 modules -------------------------------------------
from predictive_engine import (
    DatasetBuilder,
    ModelBuilder,
    PredictiveEngine,
    TFTConfig,
    TFTPredictor,
    TrainingPipeline,
)

# Re-use Phase 1's synthetic data generator
from test_pipeline import generate_synthetic_m5

# Phase 1 pipeline for generating features
from data_pipeline import DemandForecastingPipeline, PipelineConfig


# ============================================================================
# S1  GENERATE TEST DATA
# ============================================================================

def create_test_data(tmp_dir: Path) -> pd.DataFrame:
    """
    Generate synthetic M5 data, run Phase 1 pipeline, return the
    full featured DataFrame ready for Phase 2.
    """
    raw_dir = tmp_dir / "raw"
    processed_dir = tmp_dir / "processed"

    # Generate synthetic CSVs (5 items x 2 stores x 150 days)
    generate_synthetic_m5(raw_dir, n_items=5, n_days=150)

    # Run Phase 1
    config = PipelineConfig(
        data_dir=raw_dir,
        output_dir=processed_dir,
        warmup_days=30,
    )
    pipeline = DemandForecastingPipeline(config)
    pipeline.run(save=True)

    # Load the full featured dataset
    df = pd.read_parquet(processed_dir / "full_featured.parquet")
    print(f"[OK] Test data generated: {df.shape[0]:,} rows x {df.shape[1]} cols")
    return df


# ============================================================================
# S2  TESTS
# ============================================================================

def test_dataset_builder(df: pd.DataFrame):
    """Test DataFrame preparation and TimeSeriesDataSet creation."""
    print("\n--- Test: DatasetBuilder ---")

    config = TFTConfig(
        max_prediction_length=14,  # shorter for test
        max_encoder_length=30,
        min_encoder_length=10,
        batch_size=4,
    )
    builder = DatasetBuilder(config)

    # Test prepare_dataframe
    prepared = builder.prepare_dataframe(df)
    assert config.time_idx in prepared.columns, "time_idx not created"
    assert prepared[config.time_idx].dtype in [np.int32, np.int64, int], \
        f"time_idx wrong dtype: {prepared[config.time_idx].dtype}"
    print(f"  [OK] DataFrame prepared: {prepared.shape}")
    print(f"  [OK] time_idx range: [{prepared[config.time_idx].min()}, {prepared[config.time_idx].max()}]")

    # Test build_training_dataset
    training, validation = builder.build_training_dataset(prepared)
    assert len(training) > 0, "Training dataset is empty"
    assert len(validation) > 0, "Validation dataset is empty"
    print(f"  [OK] Training dataset: {len(training)} samples")
    print(f"  [OK] Validation dataset: {len(validation)} samples")

    # Test dataloaders
    train_dl, val_dl = builder.create_dataloaders(training, validation)
    assert len(train_dl) > 0, "Train dataloader is empty"
    assert len(val_dl) > 0, "Val dataloader is empty"
    print(f"  [OK] DataLoaders: {len(train_dl)} train batches, {len(val_dl)} val batches")

    # Verify a batch shape
    batch = next(iter(train_dl))
    x, y = batch
    print(f"  [OK] Batch x keys: {list(x.keys())[:5]}...")
    print(f"  [OK] Batch y shape: {y[0].shape}")

    return training, validation, train_dl, val_dl, prepared


def test_model_builder(training_dataset):
    """Test TFT model instantiation."""
    print("\n--- Test: ModelBuilder ---")

    config = TFTConfig(
        hidden_size=16,        # small for test
        attention_head_size=2,
        dropout=0.1,
        hidden_continuous_size=8,
    )
    builder = ModelBuilder(config)

    model = builder.build(training_dataset)

    # Verify model properties
    assert model is not None, "Model is None"
    n_params = sum(p.numel() for p in model.parameters())
    assert n_params > 0, "Model has no parameters"
    print(f"  [OK] Model created: {n_params:,} parameters")

    # Verify loss function
    assert isinstance(model.loss, QuantileLoss), \
        f"Expected QuantileLoss, got {type(model.loss)}"
    print(f"  [OK] Loss: QuantileLoss({model.loss.quantiles})")

    return model


def test_training_pipeline():
    """Test trainer setup and hardware detection."""
    print("\n--- Test: TrainingPipeline ---")

    config = TFTConfig(max_epochs=1)
    pipeline = TrainingPipeline(config)

    # Test hardware detection
    accel, devices = pipeline.detect_accelerator()
    assert accel in ["cpu", "gpu", "mps"], f"Unknown accelerator: {accel}"
    assert devices >= 1, f"Invalid device count: {devices}"
    print(f"  [OK] Accelerator: {accel}, devices: {devices}")

    # Test trainer setup
    trainer = pipeline.setup_trainer()
    assert trainer is not None, "Trainer is None"
    assert trainer.max_epochs == 1, f"Expected max_epochs=1, got {trainer.max_epochs}"
    print(f"  [OK] Trainer configured: max_epochs={trainer.max_epochs}")

    # Verify callbacks
    callback_types = [type(cb).__name__ for cb in trainer.callbacks]
    assert "EarlyStopping" in callback_types, "Missing EarlyStopping callback"
    assert "LearningRateMonitor" in callback_types, "Missing LR Monitor"
    assert "ModelCheckpoint" in callback_types, "Missing ModelCheckpoint"
    print(f"  [OK] Callbacks: {callback_types}")


def test_predictor(model, validation, val_dl):
    """Test prediction extraction and structuring."""
    print("\n--- Test: TFTPredictor ---")

    config = TFTConfig(
        max_prediction_length=14,
        batch_size=4,
    )
    predictor = TFTPredictor(config)

    # Generate predictions (using untrained model -- values won't be meaningful
    # but the pipeline should work)
    predictions = predictor.predict(model, validation, val_dl)

    assert isinstance(predictions, pd.DataFrame), "Predictions not a DataFrame"
    assert len(predictions) > 0, "Predictions are empty"
    assert "p10" in predictions.columns, "Missing p10 column"
    assert "p50" in predictions.columns, "Missing p50 column"
    assert "p90" in predictions.columns, "Missing p90 column"
    assert "horizon_step" in predictions.columns, "Missing horizon_step"

    # Verify non-negative
    assert (predictions["p10"] >= 0).all(), "p10 has negative values"
    assert (predictions["p50"] >= 0).all(), "p50 has negative values"
    assert (predictions["p90"] >= 0).all(), "p90 has negative values"

    # Verify quantile ordering (p10 <= p50 <= p90) on average
    # (individual violations can occur with untrained models)
    mean_p10 = predictions["p10"].mean()
    mean_p50 = predictions["p50"].mean()
    mean_p90 = predictions["p90"].mean()
    print(f"  [OK] Predictions shape: {predictions.shape}")
    print(f"  [OK] Mean quantiles: p10={mean_p10:.2f}, p50={mean_p50:.2f}, p90={mean_p90:.2f}")
    print(f"  [OK] All predictions non-negative")

    # Test evaluation
    metrics = predictor.evaluate(predictions)
    assert "mean_interval_width" in metrics, "Missing interval width metric"
    print(f"  [OK] Metrics: {metrics}")

    return predictions


def test_1epoch_training(training, validation, train_dl, val_dl, config):
    """Run a single epoch of training to verify the full loop works."""
    print("\n--- Test: 1-Epoch Training ---")

    # Use tiny model for speed
    train_config = TFTConfig(
        max_prediction_length=config.max_prediction_length,
        max_encoder_length=config.max_encoder_length,
        min_encoder_length=config.min_encoder_length,
        hidden_size=8,
        attention_head_size=1,
        hidden_continuous_size=4,
        max_epochs=1,
        patience=1,
        batch_size=4,
        learning_rate=0.01,
        output_dir=Path(tempfile.mkdtemp(prefix="tft_test_")),
        log_dir=Path(tempfile.mkdtemp(prefix="tft_logs_")),
    )

    builder = ModelBuilder(train_config)
    model = builder.build(training)

    pipeline = TrainingPipeline(train_config)
    best_model, trainer = pipeline.train(
        model, train_dl, val_dl, find_lr=False  # skip LR finder for speed
    )

    assert best_model is not None, "Training returned None model"
    assert trainer.current_epoch >= 0, "No epochs completed"
    print(f"  [OK] Training completed: {trainer.current_epoch + 1} epoch(s)")

    # Run prediction with trained model
    predictor = TFTPredictor(train_config)
    predictions = predictor.predict(best_model, validation, val_dl)
    assert len(predictions) > 0, "No predictions after training"
    print(f"  [OK] Post-training predictions: {predictions.shape}")

    # Cleanup
    shutil.rmtree(train_config.output_dir, ignore_errors=True)
    shutil.rmtree(train_config.log_dir, ignore_errors=True)

    return predictions


# ============================================================================
# S3  MAIN
# ============================================================================

def main():
    """Run all Phase 2 smoke tests."""
    print("=" * 64)
    print("  SMOKE TEST -- Phase 2: Predictive Engine (TFT)")
    print("=" * 64)

    tmp_root = Path(tempfile.mkdtemp(prefix="tft_smoke_"))

    try:
        # ---- Generate test data via Phase 1 --------------------------------
        df = create_test_data(tmp_root)

        # ---- Run component tests -------------------------------------------
        (training, validation, train_dl, val_dl,
         prepared) = test_dataset_builder(df)

        model = test_model_builder(training)

        test_training_pipeline()

        predictions = test_predictor(model, validation, val_dl)

        # ---- Run 1-epoch end-to-end training test --------------------------
        train_config = TFTConfig(
            max_prediction_length=14,
            max_encoder_length=30,
            min_encoder_length=10,
        )
        final_preds = test_1epoch_training(
            training, validation, train_dl, val_dl, train_config
        )

        print("")
        print("=" * 64)
        print("  ALL PHASE 2 TESTS PASSED")
        print("=" * 64)

    except Exception as e:
        print(f"\nTEST FAILED: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

    finally:
        shutil.rmtree(tmp_root, ignore_errors=True)
        print(f"\nCleaned up temp directory: {tmp_root}")


if __name__ == "__main__":
    # Need to import QuantileLoss here for the test
    from pytorch_forecasting.metrics import QuantileLoss
    main()
